#!/bin/bash

printUsage() {
	echo "Usage: $0 serve <width> <height>"
	echo "Usage: $0 test <width> <height>"
}

if [ "$#" -ne "3" ]; then
	printUsage
	exit
fi

case "$1" in
	serve)
		if [ ! -f bin/glem.elf ]; then
			echo "Can't locate server's binary. Perhaps you should make first"
			exit
		fi
		#./bin/glem.elf -w$2 -h$3 -s3  #  Debug
		./bin/glem.elf -w$2 -h$3 -s3 > /dev/null 2>&1 &
		;;
	test)
		if [ ! -f bin/sample.elf ]; then
			echo "Can't locate sample's binary. Perhaps you should make first"
			exit
		fi
		./bin/sample.elf $1 $2
		;;
	*)
		printUsage
esac
