.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GLEM" "1" "2017-05-01" "" ""
.
.SH "NAME"
\fBglem\fR \- A tiny Graphical LCD Emulator
.
.SH "SYNOPSIS"
\fBglem\fR \-r \fIRES\fR [\-s \fISCALE\fR, \.\.\.]
.
.SH "DESCRIPTION"
GLEM is a tiny (minimal) graphical LCD emulator for embedded platforms and other small projects that need a one\-off GUI to display some data without having to write too much GUI Code\.
.
.P
Often, embedded developers realize UI enhancements only after seeing the firmware in running on the device\. So the task of building a good UI is very time consuming\.
.
.P
This program aims to eliminate the round trip time involved in compiling, flashing, and checking the embedded device when working with GLCDs\. This is achieved by emulating a the GLCD in a window on your computer\.
.
.SH "OPTIONS"
.
.TP
\fB\-r\fR \fIRESOLUTION\fR
Resolution of GLCD in the format \fI\fBWIDTH\fRx\fBHEIGHT\fR\fR\. So a GLCD with width 128 pixels and height 64 pixels will call glem with \-r \fI128x64\fR
.
.TP
\fB\-s\fR \fISCALE\fR
Specify a pixel scale value\. Each pixel on your GLCD is represented by a cluster pixels in the shape of a square of side \fISCALE\fR\. Default is 1:2 sacaling, same as \-s2
.
.TP
\fB\-v\fR
Display verbose debug outupt\. When set, application doesn\'t go to background\.
.
.TP
\fB\-h\fR
Display a short help message\.
.
.SH "EXAMPLE"
Start the server with the your GLCD\'s resolution in pixels\. Optionally, you could scale the GLCD display so it looks good on your computers screen\. In the following example, glem is scaled 4 times (default is 2)\.
.
.IP "" 4
.
.nf

$ glem \-r 128x63 \-s4
.
.fi
.
.IP "" 0
.
.P
Once the glem server is running, you can set individual pixels on/off or write full frame buffers into to display\. See lib\-glem(3) for more details\.
.
.SH "BUGS"
Report bugs to \fIsiddharth@embedjournal\.com\fR or Create an issue at https://github\.com/cbsiddharth/glem\.git/
.
.SH "AUTHOR"
Written by Siddharth Chandrasekaran \fIsiddharth@embedjournal\.com\fR\.
.
.SH "ALSO SEE"
lib\-glem(3)
